# Generated by Django 5.2.3 on 2025-06-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
